version: '2'
services:
  db:
    image: mariadb:10.3
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=mydb
    ports:
      - 3306:3306

  php:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    links:
      - db

volumes:
  mysql-datavolume:
